### ISSUE TITLE
Feature request: Different feedback based on final or not final attempts

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-assessmentResults#74]
Putting in a feature request for feedback based on the user's final or not final attempt at an assessment

For example, in an assessment that allows for 3 attempts, after the 1st and 2nd assessment fails (the non-final attempts), the user might see:

> Sorry, you scored 45% and therefore didn't pass. Please try again.

Then, on the 3rd and final fail, they would see:

> Sorry, you only scored 45% and you have used up all of your attempts. You have failed the course.

I've found that some learning designers / scriptwriters assume that we can have different levels of attempt-based feedback because this is the case for question component feedback.

**Comment by oliverfoster** [comment]
How you thinking about implementation?
https://github.com/adaptlearning/adapt-contrib-assessmentResults/blob/d36abb5c68dbf733f7927c63fc14ca2816d70c80/schema/component.schema.json#L114-L119

Add an `_attempt` value in the bands items? `<=0` means all attempts `>0` means attempt number?

**Comment by swashbuck** [comment]
@oliverfoster To keep it simple, I think we could just rely on "not final" and "final" rather than basing it on the number of attempts? So, something like:

```
"_bands": [
  {
    "_score": 0,
    "feedback": {
      "notFinal": "Oof, you didn't get any questions right. Give it another try.",
      "final": "Wow, you utterly failed the course. Game over."
    },
    "_allowRetry": true
  },
  {
    "_score": 75,
    "feedback": {
      "notFinal": "Close, but not quite. Give it another try.",
      "final": "Sorry, but you've used your last attempt. You have failed the course."
    },
    "_allowRetry": true
  },
  {
    "_score": 100,
    "feedback": "Congratulations! You passed the course.",
    "_allowRetry": false
  }
],
```

So, `feedback` could accept either a string (as it does now) or an object with `notFinal` and `final` feedback.

Basing it on the number of attempts would be more flexible but might be overkill. I could be convinced otherwise, though.

**Comment by oliverfoster** [comment]
> feedback could accept either a string (as it does now) or an object with notFinal and final feedback.

You can't have a variable property type in the schemas, so it might have to be something more like:

```json
"_bands": [
  {
    "_score": 0,
    "feedbackNotFinal": "Oof, you didn't get any questions right. Give it another try.",
    "feedback": "Wow, you utterly failed the course. Game over.",
    "_allowRetry": true
  },
]
```

But I likes it.
